### ISSUE TITLE
文件

### ISSUE THREAD

**Issue by klingw** [WangShengguang/ccks-2020#11]
您好，请问graph_entity.csv，graph_relation.csv两个文件能够发出来吗

**Comment by WangShengguang** [comment]
这两个文件是通过代码生成的，参考
![image](https://user-images.githubusercontent.com/16357505/115644081-87716980-a350-11eb-8a9a-a0e04f66bd2d.png)

**Comment by klingw** [comment]
好的好的，非常感谢


| |
klingw
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年4月22日 ***@***.***> 写道：

这两个文件是通过代码生成的，参考

**Comment by WangShengguang** [comment]
data.py
![image](https://user-images.githubusercontent.com/16357505/115644508-49287a00-a351-11eb-9dc8-8c2829d19ab9.png)
