### ISSUE TITLE
data\\mention2ent.json不存在

### ISSUE THREAD

**Issue by nocoolsandwich** [WangShengguang/ccks-2020#16]
作者好，整个项目没看到mention2ent.json的生成。是官方提供的？

**Comment by WangShengguang** [comment]
> 作者好，整个项目没看到mention2ent.json的生成。是官方提供的？

![image](https://user-images.githubusercontent.com/16357505/119313913-a98b3e00-bca6-11eb-8929-835244e7feab.png)

**Comment by nocoolsandwich** [comment]
哎呀。真丢脸，不好意思打扰了。感谢您的回复
