### ISSUE TITLE
F1值询问

### ISSUE THREAD

**Issue by binglinchengxiash** [WangShengguang/ccks-2020#2]
感谢你的代码，请问下你的运行结果，valid F1值是多少呢？我用你的代码自己测试了2019年的ccsk数据，f1值是28%，感觉有点低，是不是我哪里运行有问题？

**Comment by WangShengguang** [comment]
应该没问题哈，搭了一下，没仔细调；忘记具体指标了，确实比较低

**Comment by binglinchengxiash** [comment]
> 应该没问题哈，搭了一下，没仔细调；忘记具体指标了，确实比较低

好的，谢谢哈
