### ISSUE TITLE
在请教一下，就是整个代码，涵盖的模块比较多，能否给个代码的执行顺序

### ISSUE THREAD

**Issue by zhaolulul** [WangShengguang/ccks-2020#5]
比如预处理之后，执行entityscore,但是发现里面需要加载    entity_score_model.pkl，但是entity_score_model.pkl如何生成呢？是调用entityscore里面的  gen_train_data吗

**Comment by WangShengguang** [comment]
对，调用训练代码的时候会自动生成这个文件； 具体模块的作用都在README.md了，看一下代码结构那个图；

**Comment by WangShengguang** [comment]
执行顺序 
    1. 数据准备 data.py 
    2. neo4j 数据库安装及数据导入
    3. 模型训练 manage.py
    4. 组合以上模型得到问答结果 qa.py

**Comment by zhaolulul** [comment]
谢谢楼主  另外，你的代码的结构真的很清晰
