### ISSUE TITLE
在数据生成entity_score_data.pkl的过程中发现需要加载加载EntityScore模型

### ISSUE THREAD

**Issue by zhaolulul** [WangShengguang/ccks-2020#6]
![image](https://user-images.githubusercontent.com/40298785/100090198-c4166300-2e8d-11eb-9de1-40a38047b898.png)

![image](https://user-images.githubusercontent.com/40298785/100090243-da242380-2e8d-11eb-9742-9bdaecb67037.png)
![image](https://user-images.githubusercontent.com/40298785/100090302-f0ca7a80-2e8d-11eb-8ce8-2e37ec6867f2.png)
![image](https://user-images.githubusercontent.com/40298785/100090343-fe800000-2e8d-11eb-8f23-766916dc813b.png)   在执行过程中发现需要  加载EntityScore模型，我在数据生成过程中需要加载EntityScore模型，怎么破，求教楼主

**Comment by WangShengguang** [comment]
有循环导入，EL导入EntityScore，EntityScore导入EL；检查下代码，这两个模块的导入不要在顶部导入，在函数内部执行前导入

**Comment by zhaolulul** [comment]
好的 谢谢楼主

**Comment by zhaolulul** [comment]
> 有循环导入，EL导入EntityScore，EntityScore导入EL；检查下代码，这两个模块的导入不要在顶部导入，在函数内部执行前导入

请教楼主，我觉得这个是EntityScore调用 gen_train_data生成数据过程中， EntityScore导入el,el导入EntityScore,然后调用entityscore模型生成数据，可是entity_score predict方法从哪里加载模型呢。

**Comment by zhaolulul** [comment]
![image](https://user-images.githubusercontent.com/40298785/100599020-7345b500-333a-11eb-9c1d-9daff5e0172e.png)
调用gen_train_data,我感觉应该要把下面的 subject_score_topn  subject_score_topn打分做筛选  注释掉

**Comment by WangShengguang** [comment]
不去掉应该也是可以的，有问题你看着改改吧。。。

**Comment by zhaolulul** [comment]
好的 谢谢楼主
