### ISSUE TITLE
你好，我再运行data.py时报错TypeError: 'charset' is an invalid keyword argument for this function，请问你你遇到过吗？

### ISSUE THREAD

**Issue by Ironeie** [WangShengguang/ccks-2020#8]
在data.py的第10行执行create_database(sqlite_db_engine.url)时，出现报错TypeError: 'charset' is an invalid keyword argument for this function，我看了看网上出现的都是前几年py2和py3不兼容时的encoding错误，我这个就是py3的版本，照理不应该有这个错啊

**Comment by WangShengguang** [comment]
那把sqlite_db_engine.url这里的?charset=utf8mb4删掉就行了；数据库这块代码暂时没用，可以不用创建数据库

**Comment by Ironeie** [comment]
> 那把sqlite_db_engine.url这里的?charset=utf8mb4删掉就行了；数据库这块代码暂时没用，可以不用创建数据库

谢谢
